#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec jekyll algolia push

curl -X DELETE "https://api.cloudflare.com/client/v4/zones/2fa02b93146397fbf2001d812ab8b31f/purge_cache" \
     -H "X-Auth-Email: CLOUD_FLARE_EMAIL" \
     -H "X-Auth-Key: CLOUD_FLARE_API_KEY" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'